[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
itertools = "0.12"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
sha2 = "0.10"
base64 = "0.22"
shuttle-runtime = "0.40"
shuttle-secrets = "0.40"
askama = { version = "0.12", features = ["mime", "mime_guess"] }
nucleo-matcher = "0.3"
router = { git = "https://github.com/AlanRandon/CLI-Apps" }

tectonic = "0.15"
pdf_render = { git = "https://github.com/pdf-rs/pdf_render" }
pdf = { git = "https://github.com/pdf-rs/pdf" }
pathfinder_export = { git = "https://github.com/servo/pathfinder" }
pulldown-cmark-escape = "0.10"
katex = "0.4"
pulldown-cmark = "0.10"
indexmap = "2.2"

hyper = { version = "1.1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http = "1.0"
http-body-util = "0.1"
bytes = "1.5"
http-serde = "2.0"
cookie = { version = "0.18", features = ["secure", "percent-encode"] }
hyper-staticfile = "0.10"
serde_urlencoded = "0.7"
