[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

[dependencies]
# html-builder = { path = "../CLI-apps/crates/html-builder" }
html-builder = { git = "https://github.com/AlanRandon/CLI-apps" }
toml = "0.7"
serde = { version = "1", features = ["derive", "rc"] }
itertools = "0.11"
thiserror = "1.0"
axum = { version = "0.6", features = ["headers", "macros"] }
tower-http = { version = "0.4", features = ["normalize-path"] }
tokio = { version = "1", features = ["full"] }
