[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

[dependencies]
# html-builder = { path = "../CLI-apps/crates/html-builder" }
html-builder = { git = "https://github.com/AlanRandon/CLI-apps" }
toml = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
itertools = "0.11"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
pulldown-cmark = "0.9"
rand = "0.8"
sha2 = "0.10"
katex = "0.4"

rocket = "0.5.0-rc.3"

shuttle-runtime = "0.26"
shuttle-static-folder = "0.26"
shuttle-secrets = "0.26"
shuttle-rocket = "0.26"

