[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
itertools = "0.12"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
pulldown-cmark = "0.9"
rand = "0.8"
sha2 = "0.10"
katex = "0.4"
base64 = "0.21"
shuttle-runtime = "0.36"
shuttle-secrets = "0.36"
askama = { version = "0.12", features = ["mime", "mime_guess"] }
nucleo-matcher = "0.3"
router = { git = "https://github.com/AlanRandon/CLI-Apps" }

hyper = { version = "1.1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
serde-querystring = "0.2"
http = "1.0"
http-body-util = "0.1"
bytes = "1.5"
http-serde = "2.0"
cookie = { version = "0.18", features = ["secure", "percent-encode"] }
