# https://github.com/shuttle-hq/shuttle/issues/703

[package]
name = "dep-installer-hack"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
shuttle-secrets = "0.40"
shuttle-runtime = "0.40"
tokio = "1"
